spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.22:3306/mysql?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.137.3
    port: 5672
    username: guest
    password: guest
env: test7
