spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weixin?characterEncoding=utf-8&useSSL=false
    password: 123456
    username: root
  jpa:
    show-sql: true
 rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
logging:
  config: classpath:logback-prod.xml
